# This is a basic workflow to help you get started with Actions 
name: Get Docker images from gcr 
env:
  NEW_REGISTRY_URL: "registry.cn-hangzhou.aliyuncs.com/baiquan/" 
  NEW_REGISTRY_URL2: "docker.io/skydoor/" 
  
on:
   push: 
     paths: 
     - '.github/workflows/**' 

jobs: 
  build: 
    runs-on: ubuntu-18.04 
    steps: 
    - uses: actions/checkout@v2
    ## 上传到阿里云镜像仓库 
    - name: 获取gcr.io镜像 
      run: | 
        docker login -u ${{ secrets.MY_ALI_REGISTRY_USER}} -p ${{ secrets.MY_ALI_REGISTRY_PASSWORD}} ${NEW_REGISTRY_URL} 
        echo "docker pull from k8s gcr io" 
        docker pull k8s.gcr.io/descheduler/descheduler:v0.22.1 
        docker tag k8s.gcr.io/descheduler/descheduler:v0.22.1 registry.cn- hangzhou.aliyuncs.com/baiquan/descheduler:v0.22.1 
        docker push registry.cn-hangzhou.aliyuncs.com/baiquan/descheduler:v0.22.1
