# This is a basic workflow to help you get started with Actions 
name: Get Docker images from gcr 
env:
  NEW_REGISTRY_URL: "registry.cn-hangzhou.aliyuncs.com/gdmcc/" 
  NEW_REGISTRY_URL2: "docker.io/skydoor/" 
  
on:
  push: 
    paths: 
      - '.github/workflows/**' 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    ## 上传到阿里云镜像仓库 
    - name: 获取gcr.io镜像 
      run: | 
        echo ${{ secrets.MY_ALI_REGISTRY_USERNAME}}
        echo ${{ secrets.MY_ALI_REGISTRY_PASSWD}}
        echo ${NEW_REGISTRY_URL} 
        docker login -u ${{ secrets.MY_ALI_REGISTRY_USERNAME}} -p ${{ secrets.MY_ALI_REGISTRY_PASSWD}} ${NEW_REGISTRY_URL} 
        echo "docker pull from k8s gcr io" 
        #docker pull k8s.gcr.io/descheduler/descheduler:v0.22.1 
        #docker tag k8s.gcr.io/descheduler/descheduler:v0.22.1 registry.cn-hangzhou.aliyuncs.com/baiquan/descheduler:v0.22.1 
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/descheduler:v0.22.1
        
        
        docker pull k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
        #docker pull k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
        #docker pull k8s.gcr.io/sig-storage/csi-resizer:v1.0.1
        #docker pull k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4
        #docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.0.2
        #docker pull k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0
        
        docker tag k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0 registry.cn-hangzhou.aliyuncs.com/baiquan/kube-webhook-certgen:v1.0
        #docker tag k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1  registry.cn-hangzhou.aliyuncs.com/baiquan/csi-node-driver-registrar:v2.0.1
        #docker tag k8s.gcr.io/sig-storage/csi-resizer:v1.0.1  registry.cn-hangzhou.aliyuncs.com/baiquan/csi-resizer:v1.0.1
        #docker tag k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4  registry.cn-hangzhou.aliyuncs.com/baiquan/csi-provisioner:v2.0.4
        #docker tag k8s.gcr.io/sig-storage/csi-attacher:v3.0.2  registry.cn-hangzhou.aliyuncs.com/baiquan/csi-attacher:v3.0.2
        #docker tag k8s.gcr.io/sig-storage/csi-snapshotter:v4.0.0  registry.cn-hangzhou.aliyuncs.com/baiquan/csi-snapshotter:v4.0.0
        
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/csi-node-driver-registrar:v2.0.1
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/csi-resizer:v1.0.1
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/csi-provisioner:v2.0.4
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/csi-attacher:v3.0.2
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/csi-snapshotter:v4.0.0
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/kube-webhook-certgen:v1.0
        
        #docker pull k8s.gcr.io/kube-apiserver:v1.21.2               
        #docker pull k8s.gcr.io/kube-controller-manager:v1.21.2      
        #docker pull k8s.gcr.io/kube-scheduler:v1.21.2               
        #docker pull k8s.gcr.io/kube-proxy:v1.21.2                   
        #docker pull k8s.gcr.io/pause:3.3                            
        #docker pull k8s.gcr.io/coredns/coredns:v1.8.0               
        #docker pull k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1        
        #docker pull k8s.gcr.io/cpa/cluster-proportional-autoscaler-amd64:1.8.5
        
        #docker tag k8s.gcr.io/kube-apiserver:v1.21.2           registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-apiserver:v1.21.2         
        #docker tag k8s.gcr.io/kube-controller-manager:v1.21.2  registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-controller-manager:v1.21.2
        #docker tag k8s.gcr.io/kube-scheduler:v1.21.2           registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-scheduler:v1.21.2         
        #docker tag k8s.gcr.io/kube-proxy:v1.21.2               registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-proxy:v1.21.2             
        #docker tag k8s.gcr.io/pause:3.3                        registry.cn-hangzhou.aliyuncs.com/gdmcc/pause:3.3                      
        #docker tag k8s.gcr.io/coredns/coredns:v1.8.0           registry.cn-hangzhou.aliyuncs.com/gdmcc/coredns:v1.8.0         
        #docker tag k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1    registry.cn-hangzhou.aliyuncs.com/gdmcc/k8s-dns-node-cache:1.21.1  
        #docker tag k8s.gcr.io/cpa/cluster-proportional-autoscaler-amd64:1.8.5  registry.cn-hangzhou.aliyuncs.com/gdmcc/cluster-proportional-autoscaler-amd64:1.8.5
        
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-apiserver:v1.21.2         
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-controller-manager:v1.21.2
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-scheduler:v1.21.2         
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-proxy:v1.21.2             
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/pause:3.3                      
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/coredns:v1.8.0         
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/k8s-dns-node-cache:1.21.1     
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/cluster-proportional-autoscaler-amd64:1.8.5
        
              
        #docker pull k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
        #docker tag k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1  registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-webhook-certgen:v1.1.1
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/kube-webhook-certgen:v1.1.1
        
        
        #docker pull gcr.io/cadvisor/cadvisor:v0.38.0
        #docker tag  gcr.io/cadvisor/cadvisor:v0.38.0  registry.cn-hangzhou.aliyuncs.com/gdmcc/cadvisor:v0.38.0
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/cadvisor:v0.38.0
        
        #docker pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        #docker tag k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 registry.cn-hangzhou.aliyuncs.com/gdmcc/nfs-subdir-external-provisioner:v4.0.2
        #docker push registry.cn-hangzhou.aliyuncs.com/gdmcc/nfs-subdir-external-provisioner:v4.0.2
 
        #docker pull kubesphere/ks-installer:v3.3.0
        #docker tag kubesphere/ks-installer:v3.3.0 registry.cn-hangzhou.aliyuncs.com/baiquan/kubesphere/ks-installer:v3.3.0
        #docker push registry.cn-hangzhou.aliyuncs.com/baiquan/kubesphere/ks-installer:v3.3.0

        docker pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        docker tag k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2  registry.cn-hangzhou.aliyuncs.com/baiquan/nfs-subdir-external-provisioner:v4.0.2
        docker pull registry.cn-hangzhou.aliyuncs.com/baiquan/nfs-subdir-external-provisioner:v4.0.2
        
        
        
 
 
